#!/usr/bin/env python3

#import urwid
import pymongo
from datetime import datetime

mongo = pymongo.MongoClient('mongodb://localhost:27017/ticky')
db = mongo.get_default_database()

inboxId = db.tasks.find_one( { '_id': 'inboxId' } )['inboxId']
#print(inboxId)

def show_list(heading, tasks, trailing_blank_line=False, width=0):
    first = True
    for task in tasks:
        if first:
            first = False
            if heading:
                print(heading)
        #bullet = "□"
        bullet = "□"
        #bullet = "▢"
        #bullet = "x"
        if task['kind'] == "CHECKLIST":
            bullet = "▤"
            #bullet = "▣"
        title = task['title']
        leading = f' {bullet} '
        print(leading + title)
    if trailing_blank_line:
        print()


def todays_day():
    return datetime.today().strftime('%Y%m%d')

def query_day(day, sort=1):
    return db.tasks.aggregate( [
            { '$match': { 'projectId': inboxId, 'status': 0, 'deleted': 0, 'dueDate': { '$exists': True } } },
            { '$addFields': { 'day': { '$dateToString': { 'date': '$dueDate', 'format': '%Y%m%d', 'timezone': '$timeZone' } } } },
            { '$match': { 'day': day } },
            { '$sort': { 'day': sort, 'isAllDay': 1, 'dueDate': 1, 'priority': -1, 'sortOrder': 1 } },
            { '$project': { '_id': 0, 'priority': 1, 'title': 1, 'dueDate': 1, 'kind': 1 } },
        ] )



show_list("TODAY", query_day(todays_day()), trailing_blank_line=True)



